image: node:18

pipelines:
  default:
    - step:
        name: "Deploy to GitHub Pages"
        script:
          # Install rsync
          - apt-get update && apt-get install -y rsync
          # Configure Git
          - git config --global user.email "rahul.borade@parseq.com"
          - git config --global user.name "Bitbucket Pipeline Bot"
          # Clone the GitHub repo into 'deploy' directory
          - git clone --depth=1 https://x-access-token:${github_token}@github.com/rahulvb-bit/rahul.github.io.git deploy
          # Use rsync to copy everything except the 'deploy' folder and the local .git folder
          - rsync -av --exclude=deploy --exclude=.git ./ deploy/
          # Move into the deploy directory
          - cd deploy
          # Stage and commit changes
          - git add .
          - git commit -m "Deployed from Bitbucket Pipelines 🚀" || echo "No changes to commit"
          # Push changes to GitHub
          - git push origin main  # Or change to 'gh-pages' if that's your target branch

